version: "3.8"
services:
  rabbitmq:

  weather-collector:

  go-worker:
    build:
      context: ./consumer-go
    container_name: go-worker
    depends_on:
      - rabbitmq
      # Nest_api
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      NESTJS_API_URL: http://nestjs-api:3000/api/weather/logs
    networks:
      - weather-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    networks:
      - weather-net

  nestjs-api:
    build:
      context: ./backend-nestjs
    container_name: nestjs-api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      MONGO_URL: mongodb://root:root@mongodb:27017/weatherdb?authSource=admin
      JWT_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    networks:
      - weather-net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

volumes:
  mongo-data:

networks:
  weather-net:
    driver: bridge
